src/bwms_app/views/register.py
from flask import Flask, flash, redirect, render_template, request, session, abort, url_for,Blueprint
from bwms_app import cursor
from bwms_app.forms import Registration_Form
import bcrypt

register_bp = Blueprint('register', __name__)

@register_bp.route('/register',methods = ['GET','POST'])
def register():
    form = Registration_Form()
    if form.validate_on_submit():
        depart_name = str(request.form.get('department'))
        print(depart_name)
        cursor.execute("Insert into temp_data_storage_table values ('"+form.email.data+"',crypt('"+ form.password.data+"',gen_salt('bf')),'" + form.username.data+"','"+ form.name.data+"','"+ depart_name+"')")
        flash("You will be notified through email regarding the registration request.")
        return redirect(url_for('login.login'))
    cursor.execute("SELECT department_name FROM departments ")
    temp = cursor.fetchall()    
    return render_template('Authentication/register.html', form= form, items = temp)

src/bwms_app/templates/Authentication/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="../static/Login_v17/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/Login_v17/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/Login_v17/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/Login_v17/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/Login_v17/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../static/Login_v17/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/Login_v17/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/Login_v17/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../static/Login_v17/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/Login_v17/css/util.css">
	<link rel="stylesheet" type="text/css" href="../static/Login_v17/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form">
					<span class="login100-form-title p-b-34">
						{% for message in get_flashed_messages() %}
            			<div class="flash">{{ message }}</div>
            			{% endfor %}
						Account Login
					</span>
					
					<div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20" data-validate="Type email">
						<input id="first-name" class="input100" type="email" name="email_id" placeholder="Email address">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 rs2-wrap-input100 validate-input m-b-20" data-validate="Type password">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100"></span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Sign in
						</button>
					</div>

					<div class="w-full text-center p-t-27 p-b-239">
						<span class="txt1">
							Forgot
						</span>

						<a href="#" class="txt2">
							Email address / password?
						</a>
					</div>

					<div class="w-full text-center">
						<a href="{{url_for('register.register')}}" class="txt3">
							Sign Up
						</a>
					</div>
				</form>

				<div class="login100-more" style="background-image: url('../static/Login_v17/images/work.png');"></div>
			</div>
		</div>
	</div>
	
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="../static/Login_v17/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="../static/Login_v17/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="../static/Login_v17/vendor/bootstrap/js/popper.js"></script>
	<script src="../static/Login_v17/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="../static/Login_v17/vendor/select2/select2.min.js"></script>
	<script>
		$(".selection-2").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});
	</script>
<!--===============================================================================================-->
	<script src="../static/Login_v17/vendor/daterangepicker/moment.min.js"></script>
	<script src="../static/Login_v17/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="../static/Login_v17/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="../static/Login_v17/js/main.js"></script>

</body>
</html>

src/bwms_app/templates/Authentication/register.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  background-color: black;
}

* {
  box-sizing: border-box;
}

/* Add padding to containers */
.container {
  padding: 16px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit button */
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity: 1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}
</style>
</head>
<body>

<form action="", method = 'post'>
  <div class="container">
    <h1>Register</h1>
    <p>Please fill in this form to create an account.</p>
    <hr>

    {{form.hidden_tag()}}
                    <div >
                        {{form.name.label}}
                        {{form.name(size = 32)}}
                        <span class="focus-input100"></span>
                    </div>
                    <div >
                        {{form.username.label}}
                        {{form.username(size = 32)}}
                        <span class="focus-input100"></span>
                    </div>
                    
                   
                    

					<div >
                        {{form.email.label}}
                        {{form.email(size= 32)}}
						
					</div>
					
                    <div >
                        {{form.password.label}}
                        {{form.password(size = 32)}}
                        <span class="focus-input100"></span>
                    </div>
                    <div>
                        {{form.password2.label}}
                        {{form.password2(size = 32)}}
                        <span class="focus-input100"></span>
                    </div>

                    <div>
                        <label for="departments">Choose department:      </label>

                        <select name ="department">
                            {% for item in items %}
                            <option value="{{ item[0] }}">{{ item[0] }}</option>
                            {% endfor %}
                        </select>

                    </div>
                    
                    <div >
                      
                        <span class="focus-input100"></span>
                    </div>
                    <br>
                    <br>
					<div >
                        {{form.submit()}}
					</div>

  </div>
  
  <div class="container signin">
    <p>Already have an account? <a href="{{url_for('login.login')}}">Sign in</a>.</p>
  </div>
</form>

</body>
</html>