src/bwms_app/views/system_admin.py
from flask import Flask, flash, redirect, render_template, request, session, abort, url_for, Blueprint
import os
from dotenv import load_dotenv
import psycopg2
import json
import datetime
from bwms_app import cursor
from bwms_app import conn
from datetime import datetime
from datetime import date

system_admin_bp = Blueprint('system_admin',__name__)


#  define the functions here and routes for system admin

@system_admin_bp.route('/system_admin/home_page')
def home_page():
    return render_template('system_admin/home_page.html')


@system_admin_bp.route('/system_admin/add_non_dept_roles',  methods=["POST", "GET"])
def add_non_dept_roles():
    if request.method == "POST":
        role_name = request.form['role_name']
        print(role_name)
        try:
            cur = conn.cursor()
            cur.execute("INSERT INTO roles_not_associated_with_department (role_name) VALUES (%s);", (role_name,))
            conn.commit()
            
        except (Exception, psycopg2.DatabaseError) as error:
            print(error)
            cur.execute('rollback')
        cur.close()
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM roles_not_associated_with_department")
        role_data = cur.fetchall()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()
    return render_template('system_admin/non_dept_roles.html', role_data=role_data)    

@system_admin_bp.route('/system_admin/delete_role/<role_name>', methods=["POST", "GET"])
def delete_non_dept_role(role_name):
    print(role_name)
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM roles_not_associated_with_department WHERE role_name = %s", [role_name])
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()
    return redirect(url_for('system_admin.add_non_dept_roles'))


@system_admin_bp.route('/system_admin/add_dept_roles',  methods=["POST", "GET"])
def add_dept_roles():
    if request.method == "POST":
        role_name = request.form['role_name']
        print(role_name)
        try:
            cur = conn.cursor()
            cur.execute("INSERT INTO roles_associated_with_department (role_name) VALUES (%s);", (role_name,))
            conn.commit()
            
        except (Exception, psycopg2.DatabaseError) as error:
            print(error)
            cur.execute('rollback')
        cur.close()
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM roles_associated_with_department")
        role_data = cur.fetchall()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()
    return render_template('system_admin/dept_roles.html', role_data=role_data)

@system_admin_bp.route('/system_admin/delete_non_dept_role/<role_name>', methods=["POST", "GET"])
def delete_dept_role(role_name):
    print(role_name)
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM roles_associated_with_department WHERE role_name = %s", [role_name])
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()
    return redirect(url_for('system_admin.add_dept_roles'))


@system_admin_bp.route('/system_admin/show_roles',  methods=["POST", "GET"])
def show_all_roles():
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM roles_not_associated_with_department")
        role_data = cur.fetchall()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM roles_associated_with_department")
        department_role_data = cur.fetchall()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()    
    return render_template('/system_admin/show_roles.html', role_data=role_data, department_role_data = department_role_data)        


@system_admin_bp.route('/system_admin/department_actions',  methods=["POST", "GET"])
def CRD_departments():
    
    if request.method == "POST":
        department = request.form['department']
        print(department)
        try:
            cur = conn.cursor()
            cur.execute("INSERT INTO departments (department_name, start_date) VALUES (%s, CURRENT_DATE);", (department,))
            conn.commit()
            
        except (Exception, psycopg2.DatabaseError) as error:
            print(error)
            cur.execute('rollback')
        cur.close()
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM departments")
        data = cur.fetchall()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()
    return render_template('system_admin/CRD_departments.html', data=data)            

# @system_admin_bp.route('/system_admin/edit_departments',  methods=["POST", "GET"])
# def edit_departments()
@system_admin_bp.route('/system_admin/delete_department/<department_name>', methods=["POST", "GET"])
def delete_department(department_name):
    print(department_name)
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM departments WHERE department_name = %s", [department_name])
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()
    return redirect(url_for('system_admin.CRD_departments'))

@system_admin_bp.route('/system_admin/show_departments',  methods=["POST", "GET"])
def show_departments():
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM departments")
        data = cur.fetchall()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()
    return render_template('/system_admin/show_departments.html', data=data)        

@system_admin_bp.route('/system_admin/delete_employee/<username>', methods=["POST", "GET"])
def delete_employee(username):
    print(username)
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM employees WHERE username = %s", [username])
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()
    return redirect(url_for('system_admin.RD_employees'))

@system_admin_bp.route('/system_admin/employees',  methods=["POST", "GET"])
def RD_employees():
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM employees")
        data = cur.fetchall()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()
    return render_template('system_admin/RD_employees.html', data=data)            


@system_admin_bp.route('/system_admin/assign_emp_non_dept_role',  methods=["POST", "GET"])
def assign_emp_non_dept_role():
    
    if request.method == "POST":
        role_name = request.form['role_name']
        post_email_id = request.form['post_email_id']
        password = request.form['password']
        username = request.form['username']
        start_date = request.form['start_date']
        
        print(username)
        print(password)
        print(post_email_id)
        try:
            cur = conn.cursor()
            cur.execute("INSERT INTO employees_holding_post_not_associated_with_department (post_email_id, password, username, start_date, role_name) VALUES (%s, %s, %s, %s ,%s);", (post_email_id, password, username, start_date, role_name,))
            conn.commit()
            
        except (Exception, psycopg2.DatabaseError) as error:
            print(error)
            cur.execute('rollback')
        cur.close()
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM roles_not_associated_with_department")
        role_data = cur.fetchall()
        cur.execute("SELECT * FROM users")
        user_data = cur.fetchall()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()
    return render_template('system_admin/assign_emp_non_dept_role.html', role_data = role_data, user_data = user_data)            

@system_admin_bp.route('/system_admin/show_assigned_role',  methods=["POST", "GET"])
def show_assigned_role():
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM employees_holding_post_not_associated_with_department")
        assigned_role_data = cur.fetchall()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        cur.execute('rollback')
    cur.close()
    return render_template('system_admin/show_assigned_role.html', assigned_role_data = assigned_role_data)            

@system_admin_bp.route('/system_admin/edit_assigned_role/<post_email_id>',  methods=["POST", "GET"])
def edit_assigned_role(post_email_id):
    
    if request.method == "POST":
        password = request.form['password']
        username = request.form['username']
        start_date = request.form['start_date']
        print(username)
        print(password)
        print(post_email_id)
        print(start_date)
        print(type(start_date))
        start_date = datetime.strptime(start_date, '%Y-%m-%d').date()
        print(start_date)
        print(type(start_date))        
        try:
            cur = conn.cursor()
            cur.execute("Update employees_holding_post_not_associated_with_department set password = %s ,  username = %s , start_date = %s where post_email_id = %s", ( password, username, start_date , post_email_id))
            conn.commit()

        except (Exception, psycopg2.DatabaseError) as error:
            print(error)
            cur.execute('rollback')
        cur.close()
        return redirect(url_for('system_admin.show_assigned_role'))
    try:
        cur = conn.cursor()

src/bwms_app/templates/system_admin/CRD_departments.html
{% extends 'system_admin/home_page.html' %}

{% block content %}
<form action="{{ url_for('system_admin.CRD_departments') }}" method="post">
              <p>Department Name:</p>
              <p><input type="text" name="department" /></p>
              <p><input type="submit" value="submit"/></p>
       </form>

<table class="table table-striped">
       <thead>
              <tr>
                         <!-- <th scope="col"> # </th>  -->
                         <th scope="col">Department Name</th>
                         <th scope="col">Start Date</th>
                         <th></th>
                         <th></th>
              </tr>
       </thead>
       <tbody>
                             {% for item in data %}
              <tr>
                     <!-- <th scope="row">1</th> -->
              <td>{{item[0]}}</td>
              <td>{{item[1]}}</td>
               <td><a href="#" class="btn btn-default pull-right">Edit</a></td>
              <td>
                     <form action="{{ url_for('system_admin.delete_department', department_name = item[0]  ) }}" method=POST>
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="submit" value="Delete" class="btn btn-danger">
                     </form>
              </td>
              </tr>
                       {% endfor %}
       </tbody>
</table>
             
{% endblock %}

src/bwms_app/templates/system_admin/RD_employees.html
{% extends 'system_admin/home_page.html' %}

{% block content %}

<table class="table table-striped">
       <thead>
              <tr>
                         <!-- <th scope="col"> # </th>  -->
                         <th scope="col">Employee Email id</th>
                         <th scope="col">User</th>
                         <th scope="col">Department</th>
                         <th></th>
                         
              </tr>
       </thead>
       <tbody>
                             {% for item in data %}
              <tr>
                   
              <td>{{item[0]}}</td>
              <td>{{item[2]}}</td>
              <td>{{item[3]}}</td>
              
              <td>
                     <form action="{{ url_for('system_admin.delete_employee', username = item[2]  ) }}" method=POST>
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="submit" value="Delete" class="btn btn-danger">
                     </form>
              </td>
              </tr>
                       {% endfor %}
       </tbody>
</table>
             
{% endblock %}

src/bwms_app/templates/system_admin/assign_emp_dept_role.html
{% extends 'system_admin/home_page.html' %}

{% block content %}
<br>
  <form action="{{ url_for('system_admin.assign_emp_dept_role') }}" method="post">
    <div class="form-row col-md-8">
      <div class="form-group col-md-4">
        <label for="role_email_id">Role Email ID</label>
        <input type="email" name="role_email_id" class="form-control" id="role_email_id" placeholder="Email">
      </div>
      <div class="form-group col-md-4">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Password">
      </div>
    </div>
    <div class="form-group col-md-4">
      <label for="employee_email_id">Employee Email id</label>
      <select name = "employee_email_id" id="employee_email_id" class="form-control">
          <option selected>Choose...</option>
          {% for item in employees_data %}
          <option value = "{{item[0]}}">{{item[0]}}</option>
          {% endfor %}
        </select>   
       </div>
    
       <div class="form-group col-md-4">
            <label for="department">Department</label>
            <select name = "department" id="department" class="form-control">
                <option selected>Choose...</option>
                {% for item in departments_data %}
                <option value = "{{item[0]}}">{{item[0]}}</option>
                {% endfor %}
              </select>   
             </div>
          

      <div class="form-group col-md-4">
        <label for="role_name">Select Role</label>
        <select name = "role_name" id="role_name" class="form-control">
          <option selected>Choose...</option>
          {% for item in role_data %}
          <option value = "{{item[0]}}">{{item[0]}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group col-md-4">
          <label for="employee_assigned_post_date">Start Date of Tenure</label>
          <input type="date" class="form-control" name="employee_assigned_post_date" >
      </div>   
      <div class="form-group col-md-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>

{% endblock %}

src/bwms_app/templates/system_admin/assign_emp_non_dept_role.html
{% extends 'system_admin/home_page.html' %}

{% block content %}
<br>
  <form action="{{ url_for('system_admin.assign_emp_non_dept_role') }}" method="post">
    <div class="form-row col-md-8">
      <div class="form-group col-md-4">
        <label for="post_email_id">Role Email ID</label>
        <input type="email" name="post_email_id" class="form-control" id="post_email_id" placeholder="Email">
      </div>
      <div class="form-group col-md-4">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Password">
      </div>
    </div>
    <div class="form-group col-md-4">
      <label for="username">Username</label>
      <select name = "username" id="username" class="form-control">
          <option selected>Choose...</option>
          {% for item in user_data %}
          <option value = "{{item[0]}}">{{item[0]}}</option>
          {% endfor %}
        </select>   
       </div>
    
      <div class="form-group col-md-4">
        <label for="role_name">Select Role</label>
        <select name = "role_name" id="role_name" class="form-control">
          <option selected>Choose...</option>
          {% for item in role_data %}
          <option value = "{{item[0]}}">{{item[0]}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group col-md-4">
          <label for="start_date">Start Date</label>
          <input type="date" class="form-control" name="start_date" >
      </div>   
      <div class="form-group col-md-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>

{% endblock %}

src/bwms_app/templates/system_admin/assign_emp_on_role.html
{% extends 'system_admin/home_page.html' %}

{% block content %}

  <form action="{{ url_for('system_admin.assign_emp_on_role') }}" method="post">
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="post_email_id">Role Email ID</label>
        <input type="email" name="post_email_id" class="form-control" id="post_email_id" placeholder="Email">
      </div>
      <div class="form-group col-md-6">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Password">
      </div>
    </div>
    <div class="form-group">
      <label for="username">Username</label>
      <input type="text" name="username" class="form-control" id="username" placeholder="username">
    </div>
    <div class="form-row">
      
      <div class="form-group col-md-4">
        <label for="role_name">Select Role</label>
        <select name = "role_name" id="role_name" class="form-control">
          <option selected>Choose...</option>
          {% for item in role_data %}
          <option value = "{{item[0]}}">{{item[0]}}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

src/bwms_app/templates/system_admin/edit_assigned_dept_role.html
{% extends 'system_admin/home_page.html' %}

{% block content %}
<br>
  <form action="{{ url_for('system_admin.edit_assigned_dept_role', role_email_id = role_email_id) }}" method="post">
    <div class="form-row col-md-8">

      <div class="form-group col-md-4">
        <label for="password">New Password</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Password">
      </div>
    </div>
    <div class="form-group col-md-4">
      <label for="employee_email_id">New Employee Email ID</label>
      <select name = "employee_email_id" id="employee_email_id" class="form-control">
          <option selected>Choose...</option>
          {% for item in employees_data %}
          <option value = "{{item[0]}}">{{item[0]}}</option>
          {% endfor %}
        </select>   
       </div>
    
      <div class="form-group col-md-4">
          <label for="employee_assigned_post_date">Start of Tenure</label>
          <input type="date" class="form-control" name="employee_assigned_post_date" >
      </div>   
      <div class="form-group col-md-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>

{% endblock %}

src/bwms_app/templates/system_admin/edit_assigned_role.html
{% extends 'system_admin/home_page.html' %}

{% block content %}
<br>
  <form action="{{ url_for('system_admin.edit_assigned_role', post_email_id = post_email_id) }}" method="post">
    <div class="form-row col-md-8">

      <div class="form-group col-md-4">
        <label for="password">New Password</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Password">
      </div>
    </div>
    <div class="form-group col-md-4">
      <label for="username">New Username</label>
      <select name = "username" id="username" class="form-control">
          <option selected>Choose...</option>
          {% for item in user_data %}
          <option value = "{{item[0]}}">{{item[0]}}</option>
          {% endfor %}
        </select>   
       </div>
    
      <div class="form-group col-md-4">
          <label for="start_date">Start Date</label>
          <input type="date" class="form-control" name="start_date" >
      </div>   
      <div class="form-group col-md-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>

{% endblock %}

src/bwms_app/templates/system_admin/home_page.html
{%extends "layout.html"%}
{%block body%}


<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{{url_for('system_admin.home_page')}}"><b>ADMIN ACTIONS</b></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('system_admin.home_page')}}">Home <span class="sr-only">(current)</span></a>
            </li>
                  <li class="nav-item active">
                      <a class="nav-link" href="{{url_for('system_admin.RD_employees')}}">Employees</a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="{{url_for('system_admin.registration_requests')}}">Registration Requests</a>
                    </li>
                    <li class="nav-item dropdown active">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Roles
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{{url_for('system_admin.show_all_roles')}}">Show Roles</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{{url_for('system_admin.add_non_dept_roles')}}">Non-Dept Roles</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{{url_for('system_admin.add_dept_roles')}}">Departmental Roles</a>
                          <div class="dropdown-divider"></div>
                        </div>
                      </li>

                      <li class="nav-item dropdown active">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Department
                          </a>
                          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{url_for('system_admin.CRD_departments')}}">Department Actions</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{url_for('system_admin.show_departments')}}">Show Departments</a>
                            
                          </div>
                        </li>
                        <li class="nav-item dropdown active">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Assign Roles
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="{{url_for('system_admin.assign_emp_non_dept_role')}}">Assign Non-Dept Roles</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="{{url_for('system_admin.assign_emp_dept_role')}}">Assign Dept Roles</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="{{url_for('system_admin.show_assigned_role')}}">Show Assigned Roles</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="{{url_for('system_admin.show_assigned_dept_role')}}">Show Assigned Dept Roles</a>
                              
                            </div>
                          </li>
            
          </ul>
        </div>
      </nav>

      {% block content%}
      {% endblock %}

{%endblock%}

src/bwms_app/templates/system_admin/non_dept_roles.html
{% extends 'system_admin/home_page.html' %}

{% block content %}

<form action="{{ url_for('system_admin.add_non_dept_roles') }}" method="post">
        <p>Role Name :</p>
        <p><input type="text" name="role_name" /></p>
        <p><input type="submit" value="submit"/></p>
 </form>

 <br>
 <hr>

 <table class="table table-striped">
        <thead>
               <tr>
                          <!-- <th scope="col"> # </th>  -->
                          <th scope="col">Role</th>
                          <th></th>
                          <th></th>
               </tr>
        </thead>
        <tbody>
                              {% for item in role_data %}
               <tr>
                      <!-- <th scope="row">1</th> -->
               <td>{{item[0]}}</td>
                <td><a href="#" class="btn btn-default pull-right">Edit</a></td>
               <td>
                      <form action="{{ url_for('system_admin.delete_non_dept_role', role_name = item[0]  ) }}" method=POST>
                             <input type="hidden" name="_method" value="DELETE">
                             <input type="submit" value="Delete" class="btn btn-danger">
                      </form>
               </td>
               </tr>
                        {% endfor %}
        </tbody>
 </table>
              

{% endblock %}

src/bwms_app/templates/system_admin/registration_requests.html
{% extends 'system_admin/home_page.html' %}

{% block content %}
{% for request in requests %}
<div style="background-color:rgba(154, 199, 201, 0.945);color:hsl(180, 1%, 13%);padding:20px;">
<p>
    <b>Name:</b> {{request[3]}} <br>
    <b>Email ID:</b> {{request[0]}} <br>
    <b>Username:</b> {{request[2]}}<br>
    <b>Department:</b> {{request[4]}}<br>
    <button type="button" onclick="window.location.href='{{ url_for( 'system_admin.action_on_request' , email=request[0],action='Approve' ) }}';">Approve</button>
    <button type="button" onclick="window.location.href='{{ url_for( 'system_admin.action_on_request' , email=request[0],action='Reject' ) }}';">Reject</button>
</p>

</div>
{% endfor %}

{% endblock %}

src/bwms_app/templates/system_admin/show_assigned_dept_role.html
{% extends 'system_admin/home_page.html' %}

{% block content %}
<h4> Present Roles</h4>

<table class="table">
    <thead>
      <tr>
        <!-- <th scope="col"> # </th>  -->
        <th scope="col">Role EmailID</th>
        <th scope="col">Employee  Email ID</th>
        <th scope="col">Department</th>
        <th scope="col">Created On</th>
        <th scope="col">Role Name</th>
        <th scope="col">Start Date of Tenure</th>
        <th>Change Employee</th>
      </tr>
    </thead>
    <tbody>
            {% for item in assigned_role_data %}
        <tr>
        <!-- <th scope="row">1</th> -->
        <td>{{item[0]}}</td>
        <td>{{item[2]}}</td>
        <td>{{item[3]}}</td>
        <td>{{item[4]}}</td>
        <td>{{item[5]}}</td>
        <td>{{item[6]}}</td>
        <td><a href="{{ url_for('system_admin.edit_assigned_dept_role', role_email_id = item[0] ) }}" class="btn btn-default pull-right">Edit</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endblock %}

src/bwms_app/templates/system_admin/show_assigned_role.html
{% extends 'system_admin/home_page.html' %}

{% block content %}
<h4> Present Roles</h4>

<table class="table">
    <thead>
      <tr>
        <!-- <th scope="col"> # </th>  -->
        <th scope="col">Post EmailID</th>
        <th scope="col">Username</th>
        <th scope="col">Start Date</th>
        <th scope="col">Role</th>
      </tr>
    </thead>
    <tbody>
            {% for item in assigned_role_data %}
        <tr>
        <!-- <th scope="row">1</th> -->
        <td>{{item[0]}}</td>
        <td>{{item[2]}}</td>
        <td>{{item[3]}}</td>
        <td>{{item[4]}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endblock %}

src/bwms_app/templates/system_admin/show_departments.html
{% extends 'system_admin/home_page.html' %}

{% block content %}

<table class="table">
        <thead>
          <tr>
            <!-- <th scope="col"> # </th>  -->
            <th scope="col">Department Name</th>
            <th scope="col">Start Date</th>
          </tr>
        </thead>
        <tbody>
                {% for item in data %}
            <tr>
            <!-- <th scope="row">1</th> -->
            <td>{{item[0]}}</td>
            <td>{{item[1]}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

{% endblock %}

src/bwms_app/templates/system_admin/show_roles.html
{% extends 'system_admin/home_page.html' %}

{% block content %}

<table class="table">
    <thead>
      <tr>
        <!-- <th scope="col"> # </th>  -->
        <th scope="col">Role Name</th>

      </tr>
    </thead>
    <tbody>
            {% for item in role_data %}
        <tr>
        <!-- <th scope="row">1</th> -->
        <td>{{item[0]}}</td>

      </tr>
      {% endfor %}
    </tbody>
  </table>



<br>
<hr>

<table class="table">
    <thead>
      <tr>
        <!-- <th scope="col"> # </th>  -->
        <th scope="col">Department Role Name</th>

      </tr>
    </thead>
    <tbody>
            {% for item in department_role_data %}
        <tr>
        <!-- <th scope="row">1</th> -->
        <td>{{item[0]}}</td>

      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}